# *Listing 7-4: Sample .gitlab-ci.yml YAML file with repetitive blocks*

image: myCompany/salesforceDXimage:latest

stages:
  - install
  - deploy
  - test

update_packages_in_SIT:
  stage: install
  script:
    - ./scripts/getInstalledPackages.sh $TARGET_ORG
    - ./scripts/updatePackages.sh $TARGET_ORG
  variables:
    - TARGET_ORG: SIT
  only:
    - /^SIT/

update_packages_in_staging:
  stage: install
  script:
    - ./scripts/getInstalledPackages.sh $TARGET_ORG
    - ./scripts/updatePackages.sh $TARGET_ORG
  variables:
    - TARGET_ORG: staging
  only:
    - master

update_packages_in_production:
  stage: install
  script:
    - ./scripts/getInstalledPackages.sh $TARGET_ORG
    - ./scripts/updatePackages.sh $TARGET_ORG
  variables:
    - TARGET_ORG: production
  only:
    - tags
    - /^v[0-9.]+$/
  when: manual
